import type { Lesson } from "../../../types";

// "Ordering Food" lessons (yue-HK). Aggregated in ./index.ts.
// GENERATED by the lesson spreadsheet pipeline (scripts/import-lessons.mjs).
// Do not hand-edit: update the lesson CSV and run
//   pnpm lessons:import <file.csv> --write
// instead — see docs/LESSON_AUTHORING.md.
export const FOOD_LESSONS: Lesson[] = [
  {
    id: "food-1",
    categoryId: "food",
    title: "Ordering at the Kopitiam",
    description: "Order food and drinks and ask for the bill",
    difficulty: "beginner",
    tags: ["food", "kopitiam", "money"],
    content: {
      vocabulary: [
        {
          english: "I want this",
          dialect: "我要呢個",
          romanization: "ngo5 jiu3 ni1 go3",
          exampleSentence: "我要呢個同埋一杯水。",
        },
        {
          english: "How much?",
          dialect: "幾多錢？",
          romanization: "gei2 do1 cin2?",
          exampleSentence: "呢個幾多錢？",
        },
        {
          english: "Bill please",
          dialect: "埋單",
          romanization: "maai4 daan1",
          exampleSentence: "唔該，埋單！",
        },
        { english: "Delicious", dialect: "好好食", romanization: "hou2 hou2 sik6" },
        { english: "Water", dialect: "水", romanization: "seoi2", exampleSentence: "唔該比杯水我。" },
        {
          english: "Kopi (local coffee)",
          dialect: "咖啡",
          romanization: "gaa3 fe1",
          exampleSentence: "唔該，一杯咖啡。",
        },
        { english: "Teh (milk tea)", dialect: "奶茶", romanization: "naai5 caa4" },
        { english: "Take away (dabao)", dialect: "打包", romanization: "daa2 baau1" },
      ],
      levels: [
        {
          level: 1,
          title: "Order Essentials",
          description: "The core phrases for ordering and paying",
          exerciseType: "flashcard",
          vocabulary: [
            {
              english: "I want this",
              dialect: "我要呢個",
              romanization: "ngo5 jiu3 ni1 go3",
              exampleSentence: "我要呢個同埋一杯水。",
            },
            {
              english: "How much?",
              dialect: "幾多錢？",
              romanization: "gei2 do1 cin2?",
              exampleSentence: "呢個幾多錢？",
            },
            {
              english: "Bill please",
              dialect: "埋單",
              romanization: "maai4 daan1",
              exampleSentence: "唔該，埋單！",
            },
            { english: "Delicious", dialect: "好好食", romanization: "hou2 hou2 sik6" },
          ],
        },
        {
          level: 2,
          title: "Drinks & Takeaway",
          description: "Ask for water, order kopi and teh, or dabao it",
          exerciseType: "matching",
          vocabulary: [
            { english: "Water", dialect: "水", romanization: "seoi2", exampleSentence: "唔該比杯水我。" },
            {
              english: "Kopi (local coffee)",
              dialect: "咖啡",
              romanization: "gaa3 fe1",
              exampleSentence: "唔該，一杯咖啡。",
            },
            { english: "Teh (milk tea)", dialect: "奶茶", romanization: "naai5 caa4" },
            { english: "Take away (dabao)", dialect: "打包", romanization: "daa2 baau1" },
          ],
        },
        {
          level: 3,
          title: "Order It Right",
          description: "Quiz yourself on all eight kopitiam phrases",
          exerciseType: "multiple-choice",
          vocabulary: [
            {
              english: "I want this",
              dialect: "我要呢個",
              romanization: "ngo5 jiu3 ni1 go3",
              exampleSentence: "我要呢個同埋一杯水。",
            },
            {
              english: "How much?",
              dialect: "幾多錢？",
              romanization: "gei2 do1 cin2?",
              exampleSentence: "呢個幾多錢？",
            },
            {
              english: "Bill please",
              dialect: "埋單",
              romanization: "maai4 daan1",
              exampleSentence: "唔該，埋單！",
            },
            { english: "Delicious", dialect: "好好食", romanization: "hou2 hou2 sik6" },
            { english: "Water", dialect: "水", romanization: "seoi2", exampleSentence: "唔該比杯水我。" },
            {
              english: "Kopi (local coffee)",
              dialect: "咖啡",
              romanization: "gaa3 fe1",
              exampleSentence: "唔該，一杯咖啡。",
            },
            { english: "Teh (milk tea)", dialect: "奶茶", romanization: "naai5 caa4" },
            { english: "Take away (dabao)", dialect: "打包", romanization: "daa2 baau1" },
          ],
        },
        {
          level: 4,
          title: "At the Kopitiam",
          description: "Complete real kopitiam sentences",
          exerciseType: "fill-blank",
          vocabulary: [
            {
              english: "I want this",
              dialect: "我要呢個",
              romanization: "ngo5 jiu3 ni1 go3",
              exampleSentence: "___同埋一杯水。",
            },
            {
              english: "How much?",
              dialect: "幾多錢？",
              romanization: "gei2 do1 cin2?",
              exampleSentence: "呢個___？",
            },
            {
              english: "Bill please",
              dialect: "埋單",
              romanization: "maai4 daan1",
              exampleSentence: "唔該，___！",
            },
            { english: "Water", dialect: "水", romanization: "seoi2", exampleSentence: "唔該比杯___我。" },
            {
              english: "Kopi (local coffee)",
              dialect: "咖啡",
              romanization: "gaa3 fe1",
              exampleSentence: "唔該，一杯___。",
            },
            { english: "Delicious", dialect: "好好食", romanization: "hou2 hou2 sik6" },
            { english: "Teh (milk tea)", dialect: "奶茶", romanization: "naai5 caa4" },
            { english: "Take away (dabao)", dialect: "打包", romanization: "daa2 baau1" },
          ],
        },
      ],
    },
  },
  {
    id: "food-2",
    categoryId: "food",
    title: "Dim Sum & Hawker Classics",
    description: "Order dim sum and hawker centre favourites",
    difficulty: "intermediate",
    tags: ["food", "dim sum", "hawker"],
    content: {
      vocabulary: [
        { english: "Dim sum", dialect: "點心", romanization: "dim2 sam1" },
        {
          english: "Char siu rice",
          dialect: "叉燒飯",
          romanization: "caa1 siu1 faan6",
          exampleSentence: "一碟叉燒飯，唔該。",
        },
        { english: "Kaya toast", dialect: "咖央多士", romanization: "gaa3 joeng1 do1 si2" },
        { english: "Wonton noodles", dialect: "雲吞麵", romanization: "wan4 tan1 min6" },
        { english: "Rice", dialect: "飯", romanization: "faan6" },
        { english: "Noodles (mee)", dialect: "麵", romanization: "min6" },
        { english: "Hot / Cold", dialect: "熱 / 凍", romanization: "jit6 / dung3" },
        { english: "Less sweet (siu dai)", dialect: "少甜", romanization: "siu2 tim4" },
      ],
      levels: [
        {
          level: 1,
          title: "Hawker Classics",
          description: "The dishes every Singaporean family knows by heart",
          exerciseType: "flashcard",
          vocabulary: [
            { english: "Dim sum", dialect: "點心", romanization: "dim2 sam1" },
            {
              english: "Char siu rice",
              dialect: "叉燒飯",
              romanization: "caa1 siu1 faan6",
              exampleSentence: "一碟叉燒飯，唔該。",
            },
            { english: "Kaya toast", dialect: "咖央多士", romanization: "gaa3 joeng1 do1 si2" },
            { english: "Wonton noodles", dialect: "雲吞麵", romanization: "wan4 tan1 min6" },
          ],
        },
        {
          level: 2,
          title: "Rice, Noodles & More",
          description: "Match the staples and how you like them served",
          exerciseType: "matching",
          vocabulary: [
            { english: "Rice", dialect: "飯", romanization: "faan6" },
            { english: "Noodles (mee)", dialect: "麵", romanization: "min6" },
            { english: "Hot / Cold", dialect: "熱 / 凍", romanization: "jit6 / dung3" },
            { english: "Less sweet (siu dai)", dialect: "少甜", romanization: "siu2 tim4" },
          ],
        },
        {
          level: 3,
          title: "Order Like a Local",
          description: "Quiz yourself on all the local favourites",
          exerciseType: "multiple-choice",
          vocabulary: [
            { english: "Dim sum", dialect: "點心", romanization: "dim2 sam1" },
            {
              english: "Char siu rice",
              dialect: "叉燒飯",
              romanization: "caa1 siu1 faan6",
              exampleSentence: "一碟叉燒飯，唔該。",
            },
            { english: "Kaya toast", dialect: "咖央多士", romanization: "gaa3 joeng1 do1 si2" },
            { english: "Wonton noodles", dialect: "雲吞麵", romanization: "wan4 tan1 min6" },
            { english: "Rice", dialect: "飯", romanization: "faan6" },
            { english: "Noodles (mee)", dialect: "麵", romanization: "min6" },
            { english: "Hot / Cold", dialect: "熱 / 凍", romanization: "jit6 / dung3" },
            { english: "Less sweet (siu dai)", dialect: "少甜", romanization: "siu2 tim4" },
          ],
        },
      ],
    },
  },
];
