import type { Lesson } from "../../../types";

// "Street Slang" lessons (yue-HK). Aggregated in ./index.ts.
// GENERATED by the lesson spreadsheet pipeline (scripts/import-lessons.mjs).
// Do not hand-edit: update the lesson CSV and run
//   pnpm lessons:import <file.csv> --write
// instead — see docs/LESSON_AUTHORING.md.
export const SLANG_LESSONS: Lesson[] = [
  {
    id: "slang-1",
    categoryId: "slang",
    title: "Everyday Slang",
    description: "Sound natural with family and friends",
    difficulty: "intermediate",
    tags: ["casual", "informal", "youth"],
    content: {
      vocabulary: [
        {
          english: "Wait a moment",
          dialect: "等陣",
          romanization: "dang2 zan6",
          exampleSentence: "等陣先，我準備緊。",
        },
        { english: "Really?", dialect: "係咩？", romanization: "hai6 me3?" },
        {
          english: "Very nice / Awesome",
          dialect: "好正",
          romanization: "hou2 zing3",
          exampleSentence: "呢間咖啡店好正！",
        },
        { english: "Cool / Beautiful", dialect: "靚", romanization: "leng3" },
        {
          english: "Hurry up",
          dialect: "快啲",
          romanization: "faai3 di1",
          exampleSentence: "快啲！要遲到喇。",
        },
        { english: "No big deal", dialect: "冇所謂", romanization: "mou5 so2 wai6" },
        { english: "Very busy", dialect: "好忙", romanization: "hou2 mong4" },
        { english: "Very tired", dialect: "好攰", romanization: "hou2 gui6" },
      ],
      levels: [
        {
          level: 1,
          title: "Sound Natural",
          description: "The everyday reactions locals use constantly",
          exerciseType: "flashcard",
          vocabulary: [
            {
              english: "Wait a moment",
              dialect: "等陣",
              romanization: "dang2 zan6",
              exampleSentence: "等陣先，我準備緊。",
            },
            { english: "Really?", dialect: "係咩？", romanization: "hai6 me3?" },
            {
              english: "Very nice / Awesome",
              dialect: "好正",
              romanization: "hou2 zing3",
              exampleSentence: "呢間咖啡店好正！",
            },
            { english: "Cool / Beautiful", dialect: "靚", romanization: "leng3" },
          ],
        },
        {
          level: 2,
          title: "Keep It Moving",
          description: "Match the slang for busy city life",
          exerciseType: "matching",
          vocabulary: [
            {
              english: "Hurry up",
              dialect: "快啲",
              romanization: "faai3 di1",
              exampleSentence: "快啲！要遲到喇。",
            },
            { english: "No big deal", dialect: "冇所謂", romanization: "mou5 so2 wai6" },
            { english: "Very busy", dialect: "好忙", romanization: "hou2 mong4" },
            { english: "Very tired", dialect: "好攰", romanization: "hou2 gui6" },
          ],
        },
        {
          level: 3,
          title: "Slang Check",
          description: "Quiz yourself on all eight slang phrases",
          exerciseType: "multiple-choice",
          vocabulary: [
            {
              english: "Wait a moment",
              dialect: "等陣",
              romanization: "dang2 zan6",
              exampleSentence: "等陣先，我準備緊。",
            },
            { english: "Really?", dialect: "係咩？", romanization: "hai6 me3?" },
            {
              english: "Very nice / Awesome",
              dialect: "好正",
              romanization: "hou2 zing3",
              exampleSentence: "呢間咖啡店好正！",
            },
            { english: "Cool / Beautiful", dialect: "靚", romanization: "leng3" },
            {
              english: "Hurry up",
              dialect: "快啲",
              romanization: "faai3 di1",
              exampleSentence: "快啲！要遲到喇。",
            },
            { english: "No big deal", dialect: "冇所謂", romanization: "mou5 so2 wai6" },
            { english: "Very busy", dialect: "好忙", romanization: "hou2 mong4" },
            { english: "Very tired", dialect: "好攰", romanization: "hou2 gui6" },
          ],
        },
        {
          level: 4,
          title: "Use It in a Sentence",
          description: "Drop the right slang into real sentences",
          exerciseType: "fill-blank",
          vocabulary: [
            {
              english: "Wait a moment",
              dialect: "等陣",
              romanization: "dang2 zan6",
              exampleSentence: "___先，我準備緊。",
            },
            {
              english: "Very nice / Awesome",
              dialect: "好正",
              romanization: "hou2 zing3",
              exampleSentence: "呢間咖啡店___！",
            },
            {
              english: "Hurry up",
              dialect: "快啲",
              romanization: "faai3 di1",
              exampleSentence: "___！要遲到喇。",
            },
            { english: "Really?", dialect: "係咩？", romanization: "hai6 me3?" },
            { english: "Cool / Beautiful", dialect: "靚", romanization: "leng3" },
            { english: "No big deal", dialect: "冇所謂", romanization: "mou5 so2 wai6" },
            { english: "Very busy", dialect: "好忙", romanization: "hou2 mong4" },
            { english: "Very tired", dialect: "好攰", romanization: "hou2 gui6" },
          ],
        },
      ],
    },
  },
  {
    id: "slang-2",
    categoryId: "slang",
    title: "Expressing Feelings",
    description: "Share how you feel in Cantonese",
    difficulty: "intermediate",
    tags: ["emotions", "expressive"],
    content: {
      vocabulary: [
        { english: "Happy", dialect: "開心", romanization: "hoi1 sam1", exampleSentence: "今日好開心！" },
        { english: "Sad", dialect: "唔開心", romanization: "m4 hoi1 sam1" },
        { english: "Scared", dialect: "驚", romanization: "geng1" },
        {
          english: "Hungry",
          dialect: "肚餓",
          romanization: "tou5 ngo6",
          exampleSentence: "我好肚餓，食乜好？",
        },
        { english: "Bored", dialect: "悶", romanization: "mun6" },
        { english: "Surprised", dialect: "好驚訝", romanization: "hou2 geng1 ngaa6" },
        {
          english: "Love it",
          dialect: "好鍾意",
          romanization: "hou2 zung1 ji3",
          exampleSentence: "我好鍾意食點心。",
        },
      ],
      levels: [
        {
          level: 1,
          title: "Core Feelings",
          description: "Say how you feel — happy, sad, scared, or hungry",
          exerciseType: "flashcard",
          vocabulary: [
            { english: "Happy", dialect: "開心", romanization: "hoi1 sam1", exampleSentence: "今日好開心！" },
            { english: "Sad", dialect: "唔開心", romanization: "m4 hoi1 sam1" },
            { english: "Scared", dialect: "驚", romanization: "geng1" },
            {
              english: "Hungry",
              dialect: "肚餓",
              romanization: "tou5 ngo6",
              exampleSentence: "我好肚餓，食乜好？",
            },
          ],
        },
        {
          level: 2,
          title: "More Moods",
          description: "Match the feelings you share every day",
          exerciseType: "matching",
          vocabulary: [
            { english: "Bored", dialect: "悶", romanization: "mun6" },
            { english: "Surprised", dialect: "好驚訝", romanization: "hou2 geng1 ngaa6" },
            {
              english: "Love it",
              dialect: "好鍾意",
              romanization: "hou2 zung1 ji3",
              exampleSentence: "我好鍾意食點心。",
            },
          ],
        },
        {
          level: 3,
          title: "How Do You Feel?",
          description: "Quiz yourself on every feeling word",
          exerciseType: "multiple-choice",
          vocabulary: [
            { english: "Happy", dialect: "開心", romanization: "hoi1 sam1", exampleSentence: "今日好開心！" },
            { english: "Sad", dialect: "唔開心", romanization: "m4 hoi1 sam1" },
            { english: "Scared", dialect: "驚", romanization: "geng1" },
            {
              english: "Hungry",
              dialect: "肚餓",
              romanization: "tou5 ngo6",
              exampleSentence: "我好肚餓，食乜好？",
            },
            { english: "Bored", dialect: "悶", romanization: "mun6" },
            { english: "Surprised", dialect: "好驚訝", romanization: "hou2 geng1 ngaa6" },
            {
              english: "Love it",
              dialect: "好鍾意",
              romanization: "hou2 zung1 ji3",
              exampleSentence: "我好鍾意食點心。",
            },
          ],
        },
        {
          level: 4,
          title: "Feelings in Context",
          description: "Complete real sentences about how you feel",
          exerciseType: "fill-blank",
          vocabulary: [
            { english: "Happy", dialect: "開心", romanization: "hoi1 sam1", exampleSentence: "今日好___！" },
            {
              english: "Hungry",
              dialect: "肚餓",
              romanization: "tou5 ngo6",
              exampleSentence: "我好___，食乜好？",
            },
            {
              english: "Love it",
              dialect: "好鍾意",
              romanization: "hou2 zung1 ji3",
              exampleSentence: "我___食點心。",
            },
            { english: "Sad", dialect: "唔開心", romanization: "m4 hoi1 sam1" },
            { english: "Scared", dialect: "驚", romanization: "geng1" },
            { english: "Bored", dialect: "悶", romanization: "mun6" },
            { english: "Surprised", dialect: "好驚訝", romanization: "hou2 geng1 ngaa6" },
          ],
        },
      ],
    },
  },
];
