import type { Lesson } from "../../../types";

// "Getting Around" lessons (yue-HK). Aggregated in ./index.ts.
// GENERATED by the lesson spreadsheet pipeline (scripts/import-lessons.mjs).
// Do not hand-edit: update the lesson CSV and run
//   pnpm lessons:import <file.csv> --write
// instead — see docs/LESSON_AUTHORING.md.
export const TRANSPORT_LESSONS: Lesson[] = [
  {
    id: "transport-1",
    categoryId: "transport",
    title: "Getting Directions",
    description: "Ask for and understand directions",
    difficulty: "beginner",
    tags: ["navigation", "MTR", "taxi"],
    content: {
      vocabulary: [
        {
          english: "Where is...?",
          dialect: "...喺邊度？",
          romanization: "...hai2 bin1 dou6?",
          exampleSentence: "廁所喺邊度？",
        },
        {
          english: "How do I get to...?",
          dialect: "點去...？",
          romanization: "dim2 heoi3...?",
          exampleSentence: "點去中環地鐵站？",
        },
        { english: "MTR / Subway", dialect: "地鐵", romanization: "dei6 tit3" },
        { english: "Bus", dialect: "巴士", romanization: "baa1 si2" },
        { english: "Taxi", dialect: "的士", romanization: "dik1 si2", exampleSentence: "唔該去尖沙咀。" },
        { english: "Here", dialect: "呢度", romanization: "ni1 dou6" },
        { english: "Turn left", dialect: "向左轉", romanization: "hoeng3 zo2 zyun3" },
        { english: "Turn right", dialect: "向右轉", romanization: "hoeng3 jau6 zyun3" },
        { english: "Go straight", dialect: "直行", romanization: "zik6 haang4" },
      ],
      levels: [
        {
          level: 1,
          title: "Asking the Way",
          description: "Ask where things are and how to get there",
          exerciseType: "flashcard",
          vocabulary: [
            {
              english: "Where is...?",
              dialect: "...喺邊度？",
              romanization: "...hai2 bin1 dou6?",
              exampleSentence: "廁所喺邊度？",
            },
            {
              english: "How do I get to...?",
              dialect: "點去...？",
              romanization: "dim2 heoi3...?",
              exampleSentence: "點去中環地鐵站？",
            },
            { english: "MTR / Subway", dialect: "地鐵", romanization: "dei6 tit3" },
            { english: "Bus", dialect: "巴士", romanization: "baa1 si2" },
            { english: "Taxi", dialect: "的士", romanization: "dik1 si2", exampleSentence: "唔該去尖沙咀。" },
          ],
        },
        {
          level: 2,
          title: "Following Directions",
          description: "Understand the answer when someone points the way",
          exerciseType: "matching",
          vocabulary: [
            { english: "Here", dialect: "呢度", romanization: "ni1 dou6" },
            { english: "Turn left", dialect: "向左轉", romanization: "hoeng3 zo2 zyun3" },
            { english: "Turn right", dialect: "向右轉", romanization: "hoeng3 jau6 zyun3" },
            { english: "Go straight", dialect: "直行", romanization: "zik6 haang4" },
          ],
        },
        {
          level: 3,
          title: "Find Your Way",
          description: "Quiz yourself on every direction phrase",
          exerciseType: "multiple-choice",
          vocabulary: [
            {
              english: "Where is...?",
              dialect: "...喺邊度？",
              romanization: "...hai2 bin1 dou6?",
              exampleSentence: "廁所喺邊度？",
            },
            {
              english: "How do I get to...?",
              dialect: "點去...？",
              romanization: "dim2 heoi3...?",
              exampleSentence: "點去中環地鐵站？",
            },
            { english: "MTR / Subway", dialect: "地鐵", romanization: "dei6 tit3" },
            { english: "Bus", dialect: "巴士", romanization: "baa1 si2" },
            { english: "Taxi", dialect: "的士", romanization: "dik1 si2", exampleSentence: "唔該去尖沙咀。" },
            { english: "Here", dialect: "呢度", romanization: "ni1 dou6" },
            { english: "Turn left", dialect: "向左轉", romanization: "hoeng3 zo2 zyun3" },
            { english: "Turn right", dialect: "向右轉", romanization: "hoeng3 jau6 zyun3" },
            { english: "Go straight", dialect: "直行", romanization: "zik6 haang4" },
          ],
        },
      ],
    },
  },
  {
    id: "transport-2",
    categoryId: "transport",
    title: "Octopus & Tickets",
    description: "Navigate fares and payment",
    difficulty: "beginner",
    tags: ["payment", "transport card"],
    content: {
      vocabulary: [
        { english: "Octopus card", dialect: "八達通", romanization: "baat3 daat6 tung1" },
        { english: "Add value", dialect: "增值", romanization: "zang1 zik6" },
        { english: "Exit", dialect: "出口", romanization: "ceot1 hau2" },
        { english: "Entrance", dialect: "入口", romanization: "jap6 hau2" },
        { english: "Platform", dialect: "月台", romanization: "jyut6 toi4" },
        { english: "Last train", dialect: "尾班車", romanization: "mei5 baan1 ce1" },
      ],
      levels: [
        {
          level: 1,
          title: "Around the Station",
          description: "Learn the words you see and use at every MTR station",
          exerciseType: "flashcard",
          vocabulary: [
            { english: "Octopus card", dialect: "八達通", romanization: "baat3 daat6 tung1" },
            { english: "Add value", dialect: "增值", romanization: "zang1 zik6" },
            { english: "Exit", dialect: "出口", romanization: "ceot1 hau2" },
            { english: "Entrance", dialect: "入口", romanization: "jap6 hau2" },
            { english: "Platform", dialect: "月台", romanization: "jyut6 toi4" },
            { english: "Last train", dialect: "尾班車", romanization: "mei5 baan1 ce1" },
          ],
        },
        {
          level: 2,
          title: "Match the Signs",
          description: "Match each station sign to its meaning",
          exerciseType: "matching",
          vocabulary: [
            { english: "Octopus card", dialect: "八達通", romanization: "baat3 daat6 tung1" },
            { english: "Add value", dialect: "增值", romanization: "zang1 zik6" },
            { english: "Exit", dialect: "出口", romanization: "ceot1 hau2" },
            { english: "Entrance", dialect: "入口", romanization: "jap6 hau2" },
            { english: "Platform", dialect: "月台", romanization: "jyut6 toi4" },
            { english: "Last train", dialect: "尾班車", romanization: "mei5 baan1 ce1" },
          ],
        },
        {
          level: 3,
          title: "Tap & Go",
          description: "Quiz yourself before you ride",
          exerciseType: "multiple-choice",
          vocabulary: [
            { english: "Octopus card", dialect: "八達通", romanization: "baat3 daat6 tung1" },
            { english: "Add value", dialect: "增值", romanization: "zang1 zik6" },
            { english: "Exit", dialect: "出口", romanization: "ceot1 hau2" },
            { english: "Entrance", dialect: "入口", romanization: "jap6 hau2" },
            { english: "Platform", dialect: "月台", romanization: "jyut6 toi4" },
            { english: "Last train", dialect: "尾班車", romanization: "mei5 baan1 ce1" },
          ],
        },
      ],
    },
  },
];
