// TypeScript source generation for the lesson spreadsheet pipeline: turns
// registry-shaped content back into src/data/lessons/<code>/ modules that
// match the existing per-language file style (one file per category plus an
// index.ts aggregator). Pure string building — no file I/O.
//
// Formatting mirrors the repo's prettier conventions (double quotes, trailing
// commas, printWidth 110 with CJK counted double-width) so a regenerated file
// diffs minimally against a hand-written one; import-lessons.mjs additionally
// runs prettier over the output before writing.

import { constSuffix, languagePrefix } from "./lessonSchema.mjs";

const PRINT_WIDTH = 110;
const INDENT = "  ";
/** Soft per-file cap; stays safely under the 800-line hard cap in scripts/check-file-sizes.mjs. */
const DEFAULT_MAX_LINES = 780;

/**
 * Generate the per-language lesson modules.
 *
 * @param {string} languageCode
 * @param {{ categories: Array<object>, lessons: Array<object> }} content
 * @param {{ maxLines?: number }} [options] chunking threshold override (tests)
 * @returns {Record<string, string>} file name -> TypeScript source
 */
export function generateModules(languageCode, content, options = {}) {
  const maxLines = options.maxLines ?? DEFAULT_MAX_LINES;
  assertCategoryGrouping(languageCode, content);

  const files = {};
  const modules = []; // { importPath, constName } in category order
  for (const category of content.categories) {
    const lessons = content.lessons.filter((lesson) => lesson.categoryId === category.id);
    const { fileBase, constBase } = moduleNames(languageCode, category.id);
    const chunks = chunkLessons(lessons, maxLines);
    chunks.forEach((chunk, index) => {
      const name = index === 0 ? fileBase : `${fileBase}-${index + 1}`;
      const constName = index === 0 ? constBase : `${constBase}_${index + 1}`;
      files[`${name}.ts`] = categoryModule(languageCode, category, constName, chunk);
      modules.push({ importPath: `./${name}`, constName });
    });
  }
  files["index.ts"] = indexModule(languageCode, content, modules);
  return files;
}

/** The generated files re-group lessons by category; refuse to silently reorder. */
function assertCategoryGrouping(languageCode, content) {
  const grouped = content.categories.flatMap((category) =>
    content.lessons.filter((lesson) => lesson.categoryId === category.id).map((lesson) => lesson.id)
  );
  const original = content.lessons.map((lesson) => lesson.id);
  if (grouped.join("\n") !== original.join("\n")) {
    throw new Error(
      `${languageCode}: lessons are not grouped by category — generated modules would reorder them. ` +
        "Keep each category's lessons together (in category order) in the CSV."
    );
  }
}

function moduleNames(languageCode, categoryId) {
  const isYue = languageCode === "yue-HK";
  const prefix = languagePrefix(languageCode);
  const base = !isYue && categoryId.startsWith(prefix) ? categoryId.slice(prefix.length) : categoryId;
  const fileBase = base.toLowerCase().replace(/[^a-z0-9-]+/g, "-");
  const shortUpper = languageCode.split("-")[0].toUpperCase();
  const constBase = `${isYue ? "" : `${shortUpper}_`}${fileBase.replace(/-/g, "_").toUpperCase()}_LESSONS`;
  return { fileBase, constBase };
}

/** Greedy chunking so each generated category file stays under maxLines. */
function chunkLessons(lessons, maxLines) {
  const overhead = 10; // imports + header comment + export wrapper
  const chunks = [];
  let current = [];
  let currentLines = overhead;
  for (const lesson of lessons) {
    const lessonLines = serializeLesson(lesson, INDENT).split("\n").length;
    if (current.length > 0 && currentLines + lessonLines > maxLines) {
      chunks.push(current);
      current = [];
      currentLines = overhead;
    }
    current.push(lesson);
    currentLines += lessonLines;
  }
  chunks.push(current); // a category always gets at least one file (possibly empty is impossible: caller filters)
  return chunks;
}

function generatedNotice() {
  return [
    "// GENERATED by the lesson spreadsheet pipeline (scripts/import-lessons.mjs).",
    "// Do not hand-edit: update the lesson CSV and run",
    "//   pnpm lessons:import <file.csv> --write",
    "// instead — see docs/LESSON_AUTHORING.md.",
  ].join("\n");
}

function categoryModule(languageCode, category, constName, lessons) {
  const body = lessons.map((lesson) => serializeLesson(lesson, INDENT)).join("\n");
  return [
    `import type { Lesson } from "../../../types";`,
    "",
    `// "${category.title}" lessons (${languageCode}). Aggregated in ./index.ts.`,
    generatedNotice(),
    `export const ${constName}: Lesson[] = [`,
    body,
    "];",
    "",
  ].join("\n");
}

function indexModule(languageCode, content, modules) {
  const suffix = constSuffix(languageCode);
  const sortedImports = [...modules].sort((a, b) => (a.importPath < b.importPath ? -1 : 1));
  const importLines = sortedImports.map(
    (module) => `import { ${module.constName} } from "${module.importPath}";`
  );
  const idNote =
    languageCode === "yue-HK"
      ? [
          "//",
          '// Lesson ids here are historical and unprefixed ("greetings", "food-1", …) —',
          "// they MUST stay exactly as-is so existing LessonProgress rows keep matching.",
        ]
      : [
          "//",
          "// Lesson id convention (src/data/lessons.ts): every non-yue lesson AND category",
          `// id MUST be prefixed with the language's short code ("${languagePrefix(languageCode)}…") so ids stay`,
          "// globally unique and LessonProgress never needs a language column.",
        ];
  const categories = content.categories.map((category) => serializeCategory(category, INDENT)).join("\n");
  const spread = modules.map((module) => `...${module.constName}`).join(", ");
  return [
    `import type { Lesson, LessonCategory } from "../../../types";`,
    ...importLines,
    "",
    `// Static lesson curriculum for the ${languageCode} language pack.`,
    "// Registered in src/data/lessons.ts (getLessonContent).",
    generatedNotice(),
    ...idNote,
    "",
    `const ${suffix}_LESSON_CATEGORIES: LessonCategory[] = [`,
    categories,
    "];",
    "",
    `const ${suffix}_LESSONS: Lesson[] = [${spread}];`,
    "",
    `export const ${suffix}_LESSON_CONTENT: { categories: LessonCategory[]; lessons: Lesson[] } = {`,
    `  categories: ${suffix}_LESSON_CATEGORIES,`,
    `  lessons: ${suffix}_LESSONS,`,
    "};",
    "",
  ].join("\n");
}

// ── TS literal serialization ────────────────────────────────────────────────

const q = (value) => JSON.stringify(value);

function serializeCategory(category, indent) {
  return objectLines(
    [
      ["id", q(category.id)],
      ["title", q(category.title)],
      ["description", q(category.description)],
      ["icon", q(category.icon)],
    ],
    indent
  );
}

function serializeLesson(lesson, indent) {
  const inner = indent + INDENT;
  const lines = [`${indent}{`];
  lines.push(`${inner}id: ${q(lesson.id)},`);
  lines.push(`${inner}categoryId: ${q(lesson.categoryId)},`);
  lines.push(`${inner}title: ${q(lesson.title)},`);
  lines.push(`${inner}description: ${q(lesson.description)},`);
  lines.push(`${inner}difficulty: ${q(lesson.difficulty)},`);
  lines.push(fittedArray("tags", lesson.tags.map(q), inner));
  lines.push(`${inner}content: {`);
  lines.push(itemArray("vocabulary", lesson.content.vocabulary, inner + INDENT, serializeVocabItem));
  if (lesson.content.levels) {
    lines.push(itemArray("levels", lesson.content.levels, inner + INDENT, serializeLevel));
  }
  lines.push(`${inner}},`);
  lines.push(`${indent}},`);
  return lines.join("\n");
}

function serializeLevel(level, indent) {
  const inner = indent + INDENT;
  const lines = [`${indent}{`];
  lines.push(`${inner}level: ${level.level},`);
  lines.push(`${inner}title: ${q(level.title)},`);
  lines.push(`${inner}description: ${q(level.description)},`);
  lines.push(`${inner}exerciseType: ${q(level.exerciseType)},`);
  lines.push(itemArray("vocabulary", level.vocabulary, inner, serializeVocabItem));
  if (level.conversation) {
    lines.push(itemArray("conversation", level.conversation, inner, serializeTurn));
  }
  lines.push(`${indent}},`);
  return lines.join("\n");
}

function serializeVocabItem(item, indent) {
  const pairs = [
    ["english", q(item.english)],
    ["cantonese", q(item.cantonese)],
    ["pronunciation", q(item.pronunciation)],
  ];
  if (item.exampleSentence !== undefined) pairs.push(["exampleSentence", q(item.exampleSentence)]);
  return objectLines(pairs, indent);
}

/** Conversation turns are always written multi-line, matching the hand-written files. */
function serializeTurn(turn, indent) {
  const inner = indent + INDENT;
  const lines = [`${indent}{`];
  lines.push(`${inner}speaker: ${q(turn.speaker)},`);
  lines.push(`${inner}english: ${q(turn.english)},`);
  lines.push(`${inner}cantonese: ${q(turn.cantonese)},`);
  lines.push(`${inner}pronunciation: ${q(turn.pronunciation)},`);
  if (turn.hint !== undefined) lines.push(`${inner}hint: ${q(turn.hint)},`);
  lines.push(`${indent}},`);
  return lines.join("\n");
}

function itemArray(key, items, indent, serializeItem) {
  if (items.length === 0) return `${indent}${key}: [],`;
  const body = items.map((item) => serializeItem(item, indent + INDENT)).join("\n");
  return `${indent}${key}: [\n${body}\n${indent}],`;
}

/** `key: [a, b]` on one line when it fits the print width, else one item per line. */
function fittedArray(key, serializedItems, indent) {
  const single = `${indent}${key}: [${serializedItems.join(", ")}],`;
  if (visualWidth(single) <= PRINT_WIDTH) return single;
  const inner = indent + INDENT;
  return [`${indent}${key}: [`, ...serializedItems.map((item) => `${inner}${item},`), `${indent}],`].join("\n");
}

/** Object literal: one line when it fits the print width, else one key per line. */
function objectLines(pairs, indent) {
  const single = `${indent}{ ${pairs.map(([key, value]) => `${key}: ${value}`).join(", ")} },`;
  if (visualWidth(single) - 1 <= PRINT_WIDTH) return single; // trailing comma is not counted by prettier
  const inner = indent + INDENT;
  return [
    `${indent}{`,
    ...pairs.map(([key, value]) => `${inner}${key}: ${value},`),
    `${indent}},`,
  ].join("\n");
}

// Prettier counts East Asian wide/fullwidth characters as two columns and
// combining marks (e.g. Tâi-lô tone diacritics) as zero. Mirror that so the
// single-line/multi-line choice matches the repo's prettier output.
const WIDE_RANGES = [
  [0x1100, 0x115f],
  [0x2e80, 0x303e],
  [0x3041, 0x33ff],
  [0x3400, 0x4dbf],
  [0x4e00, 0x9fff],
  [0xa000, 0xa4cf],
  [0xac00, 0xd7a3],
  [0xf900, 0xfaff],
  [0xfe30, 0xfe4f],
  [0xff00, 0xff60],
  [0xffe0, 0xffe6],
  [0x20000, 0x2fffd],
  [0x30000, 0x3fffd],
];

function visualWidth(text) {
  let width = 0;
  for (const char of text) {
    if (/\p{M}/u.test(char)) continue;
    const codePoint = char.codePointAt(0);
    width += WIDE_RANGES.some(([start, end]) => codePoint >= start && codePoint <= end) ? 2 : 1;
  }
  return width;
}
