import type { Lesson } from "../../../types";

// "Hokkien Basics" lessons (nan-TW). Aggregated in ./index.ts.
// GENERATED by the lesson spreadsheet pipeline (scripts/import-lessons.mjs).
// Do not hand-edit: update the lesson CSV and run
//   pnpm lessons:import <file.csv> --write
// instead — see docs/LESSON_AUTHORING.md.
export const NAN_BASICS_LESSONS: Lesson[] = [
  {
    id: "nan-greetings",
    categoryId: "nan-basics",
    title: "Greetings & Basics",
    description: "Say hello and introduce yourself in Taiwanese Hokkien",
    difficulty: "beginner",
    tags: ["greeting", "polite", "daily", "introduction"],
    content: {
      vocabulary: [
        {
          english: "Hello",
          cantonese: "你好",
          pronunciation: "lí hó",
          exampleSentence: "你好，我是{{name}}。",
        },
        {
          english: "Have you eaten? (friendly greeting)",
          cantonese: "食飽未？",
          pronunciation: "tsia̍h pá buē?",
          exampleSentence: "阿姨，食飽未？",
        },
        {
          english: "Thank you",
          cantonese: "多謝",
          pronunciation: "to-siā",
          exampleSentence: "多謝你來看我。",
        },
        {
          english: "Sorry / Excuse me",
          cantonese: "歹勢",
          pronunciation: "pháinn-sè",
          exampleSentence: "歹勢，我來晏矣。",
        },
        {
          english: "Goodbye",
          cantonese: "再會",
          pronunciation: "tsài-huē",
          exampleSentence: "我先走矣，再會！",
        },
        { english: "What's your name?", cantonese: "你叫啥物名？", pronunciation: "lí kiò siánn-mih miâ?" },
        {
          english: "My name is...",
          cantonese: "我叫…",
          pronunciation: "guá kiò...",
          exampleSentence: "我叫{{name}}，請多指教。",
        },
        { english: "Nice to meet you", cantonese: "真歡喜熟似你", pronunciation: "tsin huann-hí si̍k-sāi lí" },
      ],
      levels: [
        {
          level: 1,
          title: "First Hellos",
          description: "The four phrases every visit starts with",
          exerciseType: "flashcard",
          vocabulary: [
            {
              english: "Hello",
              cantonese: "你好",
              pronunciation: "lí hó",
              exampleSentence: "你好，我是{{name}}。",
            },
            {
              english: "Have you eaten? (friendly greeting)",
              cantonese: "食飽未？",
              pronunciation: "tsia̍h pá buē?",
              exampleSentence: "阿姨，食飽未？",
            },
            {
              english: "Thank you",
              cantonese: "多謝",
              pronunciation: "to-siā",
              exampleSentence: "多謝你來看我。",
            },
            {
              english: "Goodbye",
              cantonese: "再會",
              pronunciation: "tsài-huē",
              exampleSentence: "我先走矣，再會！",
            },
          ],
        },
        {
          level: 2,
          title: "Greet It Right",
          description: "Quiz yourself on all eight greeting phrases",
          exerciseType: "multiple-choice",
          vocabulary: [
            { english: "Hello", cantonese: "你好", pronunciation: "lí hó" },
            {
              english: "Have you eaten? (friendly greeting)",
              cantonese: "食飽未？",
              pronunciation: "tsia̍h pá buē?",
            },
            { english: "Thank you", cantonese: "多謝", pronunciation: "to-siā" },
            { english: "Sorry / Excuse me", cantonese: "歹勢", pronunciation: "pháinn-sè" },
            { english: "Goodbye", cantonese: "再會", pronunciation: "tsài-huē" },
            {
              english: "What's your name?",
              cantonese: "你叫啥物名？",
              pronunciation: "lí kiò siánn-mih miâ?",
            },
            { english: "My name is...", cantonese: "我叫…", pronunciation: "guá kiò..." },
            {
              english: "Nice to meet you",
              cantonese: "真歡喜熟似你",
              pronunciation: "tsin huann-hí si̍k-sāi lí",
            },
          ],
        },
      ],
    },
  },
  {
    id: "nan-food",
    categoryId: "nan-basics",
    title: "Eating Out",
    description: "Order food and settle the bill at a Taiwanese eatery",
    difficulty: "beginner",
    tags: ["food", "restaurant", "money"],
    content: {
      vocabulary: [
        {
          english: "I want this",
          cantonese: "我欲這个",
          pronunciation: "guá beh tsit-ê",
          exampleSentence: "頭家，我欲這个。",
        },
        {
          english: "How much?",
          cantonese: "偌濟錢？",
          pronunciation: "guā-tsē tsînn?",
          exampleSentence: "這个偌濟錢？",
        },
        {
          english: "Delicious",
          cantonese: "好食",
          pronunciation: "hó-tsia̍h",
          exampleSentence: "這碗麵真好食！",
        },
        {
          english: "Boss / shopkeeper",
          cantonese: "頭家",
          pronunciation: "thâu-ke",
          exampleSentence: "頭家，借問一下。",
        },
        {
          english: "Bill, please",
          cantonese: "算數",
          pronunciation: "sǹg-siàu",
          exampleSentence: "頭家，算數！",
        },
        { english: "Water", cantonese: "水", pronunciation: "tsuí" },
        { english: "Tea", cantonese: "茶", pronunciation: "tê" },
        {
          english: "I'm hungry",
          cantonese: "我腹肚枵",
          pronunciation: "guá pak-tóo iau",
          exampleSentence: "我腹肚枵矣，來去食飯。",
        },
      ],
      levels: [
        {
          level: 1,
          title: "Order Essentials",
          description: "The core phrases for ordering and paying",
          exerciseType: "flashcard",
          vocabulary: [
            {
              english: "I want this",
              cantonese: "我欲這个",
              pronunciation: "guá beh tsit-ê",
              exampleSentence: "頭家，我欲這个。",
            },
            {
              english: "How much?",
              cantonese: "偌濟錢？",
              pronunciation: "guā-tsē tsînn?",
              exampleSentence: "這个偌濟錢？",
            },
            {
              english: "Bill, please",
              cantonese: "算數",
              pronunciation: "sǹg-siàu",
              exampleSentence: "頭家，算數！",
            },
            {
              english: "Delicious",
              cantonese: "好食",
              pronunciation: "hó-tsia̍h",
              exampleSentence: "這碗麵真好食！",
            },
          ],
        },
        {
          level: 2,
          title: "Order It Right",
          description: "Quiz yourself on all eight eating-out phrases",
          exerciseType: "multiple-choice",
          vocabulary: [
            { english: "I want this", cantonese: "我欲這个", pronunciation: "guá beh tsit-ê" },
            { english: "How much?", cantonese: "偌濟錢？", pronunciation: "guā-tsē tsînn?" },
            { english: "Delicious", cantonese: "好食", pronunciation: "hó-tsia̍h" },
            { english: "Boss / shopkeeper", cantonese: "頭家", pronunciation: "thâu-ke" },
            { english: "Bill, please", cantonese: "算數", pronunciation: "sǹg-siàu" },
            { english: "Water", cantonese: "水", pronunciation: "tsuí" },
            { english: "Tea", cantonese: "茶", pronunciation: "tê" },
            { english: "I'm hungry", cantonese: "我腹肚枵", pronunciation: "guá pak-tóo iau" },
          ],
        },
      ],
    },
  },
];
