import type { Lesson } from "../../../types";

// "Hokkien Basics" lessons (nan-TW). Aggregated in ./index.ts.
// GENERATED by the lesson spreadsheet pipeline (scripts/import-lessons.mjs).
// Do not hand-edit: update the lesson CSV and run
//   pnpm lessons:import <file.csv> --write
// instead — see docs/LESSON_AUTHORING.md.
export const NAN_BASICS_LESSONS: Lesson[] = [
  {
    id: "nan-greetings",
    categoryId: "nan-basics",
    title: "Greetings & Basics",
    description: "Say hello and introduce yourself in Singapore Hokkien",
    difficulty: "beginner",
    tags: ["greeting", "polite", "daily", "introduction"],
    content: {
      vocabulary: [
        { english: "Hello", dialect: "你好", romanization: "lí hó", exampleSentence: "你好，我是{{name}}。" },
        {
          english: "Have you eaten? (friendly greeting)",
          dialect: "食飽未？",
          romanization: "tsia̍h pá buē?",
          exampleSentence: "阿姨，食飽未？",
        },
        { english: "Thank you", dialect: "多謝", romanization: "to-siā", exampleSentence: "多謝你來看我。" },
        {
          english: "Sorry / Excuse me",
          dialect: "歹勢",
          romanization: "pháinn-sè",
          exampleSentence: "歹勢，我來晏矣。",
        },
        {
          english: "Goodbye",
          dialect: "再會",
          romanization: "tsài-huē",
          exampleSentence: "我先走矣，再會！",
        },
        { english: "What's your name?", dialect: "你叫啥物名？", romanization: "lí kiò siánn-mih miâ?" },
        {
          english: "My name is...",
          dialect: "我叫…",
          romanization: "guá kiò...",
          exampleSentence: "我叫{{name}}，請多指教。",
        },
        { english: "Nice to meet you", dialect: "真歡喜熟似你", romanization: "tsin huann-hí si̍k-sāi lí" },
      ],
      levels: [
        {
          level: 1,
          title: "First Hellos",
          description: "The four phrases every visit starts with",
          exerciseType: "flashcard",
          vocabulary: [
            {
              english: "Hello",
              dialect: "你好",
              romanization: "lí hó",
              exampleSentence: "你好，我是{{name}}。",
            },
            {
              english: "Have you eaten? (friendly greeting)",
              dialect: "食飽未？",
              romanization: "tsia̍h pá buē?",
              exampleSentence: "阿姨，食飽未？",
            },
            {
              english: "Thank you",
              dialect: "多謝",
              romanization: "to-siā",
              exampleSentence: "多謝你來看我。",
            },
            {
              english: "Goodbye",
              dialect: "再會",
              romanization: "tsài-huē",
              exampleSentence: "我先走矣，再會！",
            },
          ],
        },
        {
          level: 2,
          title: "Greet It Right",
          description: "Quiz yourself on all eight greeting phrases",
          exerciseType: "multiple-choice",
          vocabulary: [
            { english: "Hello", dialect: "你好", romanization: "lí hó" },
            {
              english: "Have you eaten? (friendly greeting)",
              dialect: "食飽未？",
              romanization: "tsia̍h pá buē?",
            },
            { english: "Thank you", dialect: "多謝", romanization: "to-siā" },
            { english: "Sorry / Excuse me", dialect: "歹勢", romanization: "pháinn-sè" },
            { english: "Goodbye", dialect: "再會", romanization: "tsài-huē" },
            { english: "What's your name?", dialect: "你叫啥物名？", romanization: "lí kiò siánn-mih miâ?" },
            { english: "My name is...", dialect: "我叫…", romanization: "guá kiò..." },
            {
              english: "Nice to meet you",
              dialect: "真歡喜熟似你",
              romanization: "tsin huann-hí si̍k-sāi lí",
            },
          ],
        },
      ],
    },
  },
  {
    id: "nan-food",
    categoryId: "nan-basics",
    title: "Eating Out",
    description: "Order food and settle the bill at the kopitiam",
    difficulty: "beginner",
    tags: ["food", "kopitiam", "money"],
    content: {
      vocabulary: [
        {
          english: "I want this",
          dialect: "我欲這个",
          romanization: "guá beh tsit-ê",
          exampleSentence: "頭家，我欲這个。",
        },
        {
          english: "How much?",
          dialect: "偌濟鐳？",
          romanization: "guā-tsē lui?",
          exampleSentence: "這个偌濟鐳？",
        },
        {
          english: "Delicious",
          dialect: "好食",
          romanization: "hó-tsia̍h",
          exampleSentence: "這碗麵真好食！",
        },
        {
          english: "Boss / shopkeeper",
          dialect: "頭家",
          romanization: "thâu-ke",
          exampleSentence: "頭家，借問一下。",
        },
        {
          english: "Bill, please",
          dialect: "算數",
          romanization: "sǹg-siàu",
          exampleSentence: "頭家，算數！",
        },
        {
          english: "Kopi (coffee)",
          dialect: "咖啡",
          romanization: "ko-pi",
          exampleSentence: "頭家，一杯咖啡。",
        },
        { english: "Teh (tea)", dialect: "茶", romanization: "tê" },
        {
          english: "I'm hungry",
          dialect: "我腹肚枵",
          romanization: "guá pak-tóo iau",
          exampleSentence: "我腹肚枵矣，來去食飯。",
        },
      ],
      levels: [
        {
          level: 1,
          title: "Order Essentials",
          description: "The core phrases for ordering and paying",
          exerciseType: "flashcard",
          vocabulary: [
            {
              english: "I want this",
              dialect: "我欲這个",
              romanization: "guá beh tsit-ê",
              exampleSentence: "頭家，我欲這个。",
            },
            {
              english: "How much?",
              dialect: "偌濟鐳？",
              romanization: "guā-tsē lui?",
              exampleSentence: "這个偌濟鐳？",
            },
            {
              english: "Bill, please",
              dialect: "算數",
              romanization: "sǹg-siàu",
              exampleSentence: "頭家，算數！",
            },
            {
              english: "Delicious",
              dialect: "好食",
              romanization: "hó-tsia̍h",
              exampleSentence: "這碗麵真好食！",
            },
          ],
        },
        {
          level: 2,
          title: "Order It Right",
          description: "Quiz yourself on all eight eating-out phrases",
          exerciseType: "multiple-choice",
          vocabulary: [
            { english: "I want this", dialect: "我欲這个", romanization: "guá beh tsit-ê" },
            { english: "How much?", dialect: "偌濟鐳？", romanization: "guā-tsē lui?" },
            { english: "Delicious", dialect: "好食", romanization: "hó-tsia̍h" },
            { english: "Boss / shopkeeper", dialect: "頭家", romanization: "thâu-ke" },
            { english: "Bill, please", dialect: "算數", romanization: "sǹg-siàu" },
            {
              english: "Kopi (coffee)",
              dialect: "咖啡",
              romanization: "ko-pi",
              exampleSentence: "頭家，一杯咖啡。",
            },
            { english: "Teh (tea)", dialect: "茶", romanization: "tê" },
            { english: "I'm hungry", dialect: "我腹肚枵", romanization: "guá pak-tóo iau" },
          ],
        },
      ],
    },
  },
];
