import type { Lesson, LessonCategory } from "../../../types";
import { NAN_BASICS_LESSONS } from "./basics";

// Static lesson curriculum for the nan-TW language pack.
// Registered in src/data/lessons.ts (getLessonContent).
// GENERATED by the lesson spreadsheet pipeline (scripts/import-lessons.mjs).
// Do not hand-edit: update the lesson CSV and run
//   pnpm lessons:import <file.csv> --write
// instead — see docs/LESSON_AUTHORING.md.
//
// Lesson id convention (src/data/lessons.ts): every non-yue lesson AND category
// id MUST be prefixed with the language's short code ("nan-…") so ids stay
// globally unique and LessonProgress never needs a language column.

const NAN_TW_LESSON_CATEGORIES: LessonCategory[] = [
  {
    id: "nan-basics",
    title: "Hokkien Basics",
    description: "Everyday Taiwanese Hokkien, from hello to the bill",
    icon: "🏮",
  },
];

const NAN_TW_LESSONS: Lesson[] = [...NAN_BASICS_LESSONS];

export const NAN_TW_LESSON_CONTENT: { categories: LessonCategory[]; lessons: Lesson[] } = {
  categories: NAN_TW_LESSON_CATEGORIES,
  lessons: NAN_TW_LESSONS,
};
